version: '3.8'

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npx @mui/envinfo

volumes:
  node_modules: 